framework:
    messenger:

        buses:
            messenger.bus.default:
                default_middleware: false
                middleware:
                    - reject_redelivered_message_middleware
                    - validation
                    - add_bus_name_stamp_middleware: ['messenger.bus.default']
                    - dispatch_after_current_bus
                    - send_message
                    - failed_message_processing_middleware
                    - handle_message

        transports:

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: '%env(MESSENGER_EXCHANGE_NAME)%'
                        type: direct
                        flags: 2
                        default_publish_routing_key: '%env(MESSENGER_ROUTING_KEY)%'
                    queues:
                        'logs.ingest':
                            flags: 2
                            binding_keys: ['%env(MESSENGER_ROUTING_KEY)%']
                            arguments:
                                x-max-priority: '%env(int:MESSENGER_QUEUE_MAX_PRIORITY)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 5

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
